nginx:
  image: hydra11/nginx
  ports:
    - "80:80"
    - "443:443"
  volumes:
    - ./data/nginx.https.conf:/etc/nginx/nginx.conf:ro
    - /etc/letsencrypt/live/jovipro.com/fullchain.pem:/etc/nginx/ssl/jovipro.com.crt
    - /etc/letsencrypt/live/jovipro.com/privkey.pem:/etc/nginx/ssl/jovipro.com.key
  net: host
  restart: always
