mc:
  image: itzg/minecraft-server:latest
  ports:
    - "25565:25565"
  environment:
    - EULA=TRUE
    - JVM_OPTS=-Xmx512M -Xms512M
    - SERVER_NAME=OP
    - ICON=https://blog.jovipro.com/sites/default/files/server-icon.png
    - OPS=EternalJovi
    - WHITELIST=EternalJovi
    - MAX_PLAYERS=5
    - DIFFICULTY=hard
    - ANNOUNCE_PLAYER_ACHIEVEMENTS=true
    - ENABLE_COMMAND_BLOCK=true
    - MAX_BUILD_HEIGHT=256
    - SPAWN_ANIMALS=true
  volumes:
    - ./data:/data
  restart: always
