version: '3'

networks:
  cache_network:
    driver: bridge

services:
  redis_master:
    image: 'bitnami/redis:latest'
    networks:
      - cache_network
    ports:
      - '6379'
    environment:
      - REDIS_REPLICATION_MODE=master
      - REDIS_PASSWORD=saber
    volumes:
      - './data/master:/bitnami'
    restart: always

  redis_replica:
    image: 'bitnami/redis:latest'
    networks:
      - cache_network
    ports:
      - '6379'
    depends_on:
      - redis_master
    environment:
      - REDIS_REPLICATION_MODE=slave
      - REDIS_MASTER_HOST=redis_master
      - REDIS_MASTER_PORT_NUMBER=6379
      - REDIS_MASTER_PASSWORD=saber
      - REDIS_PASSWORD=lancelot
    volumes:
      - './data/replica:/bitnami'
    restart: always
